### ISSUE TITLE
[Doc] install on recalbox 

### ISSUE THREAD

**Issue by MikaXII** [neolao/recalbox-api#1]
This [doc](https://github.com/neolao/recalbox-api/blob/1.0.x/documentation/install-on-recalbox.md) will be deprecated for the coming pre-release (3.3b15).

I make a buildroot package of your project. See [wiki's page](https://github.com/digitalLumberjack/recalbox-os/wiki/Recalbox-API-RESTFUL-(EN))

**Comment by neolao** [comment]
Done
